import type { BoostDef, GiftFlavor, StationDef, UpgradeDef } from "./types";

export const GRID_W = 9;
export const GRID_H = 7;

export const GIFT_INTERVAL = 60;
export const GIFT_BOOST = 60;
export const GIFT_DESPAWN = 28;
export const GIFT_FIRST = 12;
export const GIFT_MULT = 3;

export const STATIONS: StationDef[] = [
  {
    id: "cardboard",
    name: "Storage-Unit Desk",
    blurb: "A door on two crates. This is where Halcyon ends.",
    cost: 0,
    baseRate: 2.4,
    col: 1,
    row: 1,
    furn: 0,
    staff: 0,
    buff: 0,
    scale: 0.92,
    character: {
      name: "Rae Voss",
      role: "Founder",
      quote: "They fired me at 11:47. We open at midnight.",
      portrait: 0,
    },
  },
  {
    id: "ikea",
    name: "Flat-Pack Desk",
    blurb: "Nico built it without the instructions. Then he built payroll.",
    cost: 22,
    baseRate: 7.5,
    col: 3,
    row: 1,
    furn: 1,
    staff: 0,
    buff: 0,
    scale: 1,
    character: {
      name: "Nico Pell",
      role: "Ops",
      quote: "If I can build this desk, I can build a company.",
      portrait: 4,
    },
  },
  {
    id: "dual",
    name: "Dual Monitors",
    blurb: "One screen for the bug. One for the company that caused it.",
    cost: 110,
    baseRate: 24,
    col: 5,
    row: 1,
    furn: 2,
    staff: 0,
    buff: 0,
    scale: 1.08,
    character: {
      name: "Samira El-Amin",
      role: "Engineer",
      quote: "Halcyon's stack is a haunted house. I have the keys.",
      portrait: 5,
    },
  },
  {
    id: "standing",
    name: "Standing Desk",
    blurb: "Bo does not sit down for people who sat on our careers.",
    cost: 420,
    baseRate: 78,
    col: 7,
    row: 1,
    furn: 3,
    staff: 1,
    buff: 0,
    scale: 1.05,
    character: {
      name: "Bo Calder",
      role: "Product",
      quote: "We ship before their standup even starts.",
      portrait: 4,
    },
  },
  {
    id: "intern",
    name: "Intern Cubicle",
    blurb: "Jules asked if equity is taxable. Then shipped three features.",
    cost: 1600,
    baseRate: 250,
    col: 1,
    row: 3,
    furn: 4,
    staff: 1,
    buff: 0,
    scale: 1.1,
    character: {
      name: "Jules Park",
      role: "Intern",
      quote: "I kept the rejection email. As a poster.",
      portrait: 1,
    },
  },
  {
    id: "coffee",
    name: "Espresso Bar",
    blurb: "The real infrastructure. Permanent +15% income.",
    cost: 6200,
    baseRate: 820,
    col: 3,
    row: 3,
    furn: 5,
    staff: 1,
    buff: 0.15,
    scale: 1.05,
    character: {
      name: "Kenji Mori",
      role: "Barista-CTO",
      quote: "The stack is espresso, then TypeScript.",
      portrait: 2,
    },
  },
  {
    id: "team",
    name: "Team Pod",
    blurb: "Four people. One channel. No more 'circle back'.",
    cost: 24000,
    baseRate: 2700,
    col: 5,
    row: 3,
    furn: 6,
    staff: 3,
    buff: 0,
    scale: 1.18,
    character: {
      name: "Anya, Dev & Lin",
      role: "The Pod",
      quote: "We pair. We ship. We do not 'take it offline'.",
      portrait: 1,
    },
  },
  {
    id: "conference",
    name: "Conference Room",
    blurb: "Marisol allows one meeting. Then she invoices it.",
    cost: 96000,
    baseRate: 8800,
    col: 7,
    row: 3,
    furn: 6,
    staff: 2,
    buff: 0,
    scale: 1.22,
    character: {
      name: "Marisol Vega",
      role: "Counsel",
      quote: "I will allow this meeting. Once.",
      portrait: 6,
    },
  },
  {
    id: "sales",
    name: "Sales Floor",
    blurb: "Priya does not chase. She arrives with a signed term sheet.",
    cost: 380000,
    baseRate: 29000,
    col: 1,
    row: 5,
    furn: 4,
    staff: 4,
    buff: 0,
    scale: 1.12,
    character: {
      name: "Priya Raman",
      role: "Closer",
      quote: "Their 'no' is a delayed yes with worse timing.",
      portrait: 3,
    },
  },
  {
    id: "server",
    name: "Server Closet",
    blurb: "Theo lives here. The fan is a lullaby. Permanent +20%.",
    cost: 1.5e6,
    baseRate: 96000,
    col: 3,
    row: 5,
    furn: 7,
    staff: 1,
    buff: 0.2,
    scale: 1.15,
    character: {
      name: "Theo Finch",
      role: "Sysadmin",
      quote: "If the lights blink in sync, we already won.",
      portrait: 7,
    },
  },
  {
    id: "design",
    name: "Design Studio",
    blurb: "Cass makes the product feel like it already went public.",
    cost: 5.8e6,
    baseRate: 320000,
    col: 5,
    row: 5,
    furn: 2,
    staff: 2,
    buff: 0,
    scale: 1.1,
    character: {
      name: "Cass Wei",
      role: "Design",
      quote: "Make it feel expensive. Then make it true.",
      portrait: 5,
    },
  },
  {
    id: "trading",
    name: "Trading Pit",
    blurb: "Omar treats volatility like weather. He packed a coat.",
    cost: 2.2e7,
    baseRate: 1.1e6,
    col: 7,
    row: 5,
    furn: 2,
    staff: 3,
    buff: 0,
    scale: 1.14,
    character: {
      name: "Omar Haddad",
      role: "Markets",
      quote: "Their stock is a story. Ours is a machine.",
      portrait: 7,
    },
  },
  {
    id: "csuite",
    name: "Corner Office",
    blurb: "Glass so Halcyon can watch. Permanent +35%.",
    cost: 8.6e7,
    baseRate: 3.8e6,
    col: 2,
    row: 6,
    furn: 3,
    staff: 2,
    buff: 0.35,
    scale: 1.2,
    character: {
      name: "Rae Voss",
      role: "CEO",
      quote: "The glass door is so they can see us coming.",
      portrait: 0,
    },
  },
  {
    id: "datacenter",
    name: "Data Hall",
    blurb: "Compound interest, but with fans.",
    cost: 3.4e8,
    baseRate: 1.3e7,
    col: 4,
    row: 6,
    furn: 7,
    staff: 2,
    buff: 0.1,
    scale: 1.25,
    character: {
      name: "The Hum",
      role: "Infrastructure",
      quote: "We do not sleep. We accrue.",
      portrait: 2,
    },
  },
  {
    id: "helipad",
    name: "Helipad",
    blurb: "Landing on the building that fired her.",
    cost: 1.35e9,
    baseRate: 4.8e7,
    col: 6,
    row: 6,
    furn: -1,
    staff: 1,
    buff: 0.1,
    scale: 1.3,
    character: {
      name: "Captain Ilya",
      role: "Pilot",
      quote: "Halcyon's roof. Our landing.",
      portrait: 4,
    },
  },
];

export const STATION_BY_ID = Object.fromEntries(STATIONS.map((s) => [s.id, s])) as Record<
  string,
  StationDef
>;

export const GIFTS: GiftFlavor[] = [
  {
    id: "courier",
    name: "Night Courier",
    from: "A client who still works nights",
    blurb: "3× income for 60 seconds. Do not ask who sent it.",
  },
  {
    id: "angel",
    name: "Angel Basket",
    from: "The seed investor who kept the receipt",
    blurb: "Fruit, a note, and 3× revenue for a minute.",
  },
  {
    id: "halcyon",
    name: "Halcyon Leak",
    from: "A guilty former coworker",
    blurb: "Their pipeline. Our 3×. Sixty seconds of justice.",
  },
  {
    id: "kenji",
    name: "Reserve Beans",
    from: "Kenji, off the books",
    blurb: "The good bag. The floor runs 3× until it cools.",
  },
];

export const BOOSTS: BoostDef[] = [
  {
    id: "coffee",
    name: "Coffee Rush",
    blurb: "2× income. Kenji's good beans.",
    mult: 2,
    duration: 30,
    cooldown: 80,
    kind: "income",
    instantSeconds: 0,
    costFactor: 0.32,
    minCost: 12,
  },
  {
    id: "overtime",
    name: "Overtime",
    blurb: "3× income. Lights stay on. Rae does not.",
    mult: 3,
    duration: 20,
    cooldown: 110,
    kind: "income",
    instantSeconds: 0,
    costFactor: 0.38,
    minCost: 40,
  },
  {
    id: "allhands",
    name: "All-Hands",
    blurb: "5× click power. Everyone is on mute except Jules.",
    mult: 5,
    duration: 25,
    cooldown: 90,
    kind: "click",
    instantSeconds: 0,
    costFactor: 0.28,
    minCost: 18,
  },
  {
    id: "vc",
    name: "VC Drop",
    blurb: "Instant cash. They did not read the deck. Priya did.",
    mult: 1,
    duration: 0,
    cooldown: 150,
    kind: "instant",
    instantSeconds: 55,
    costFactor: 0.42,
    minCost: 30,
  },
  {
    id: "hackathon",
    name: "Hackathon",
    blurb: "4× income. Samira's weekend. Pizza is a food group.",
    mult: 4,
    duration: 40,
    cooldown: 180,
    kind: "income",
    instantSeconds: 0,
    costFactor: 0.4,
    minCost: 80,
  },
  {
    id: "press",
    name: "Press Cycle",
    blurb: "2.5× income. We are thrilled to announce the end of Halcyon.",
    mult: 2.5,
    duration: 50,
    cooldown: 160,
    kind: "income",
    instantSeconds: 0,
    costFactor: 0.36,
    minCost: 60,
  },
];

export const BOOST_BY_ID = Object.fromEntries(BOOSTS.map((b) => [b.id, b])) as Record<
  string,
  BoostDef
>;

export const UPGRADES: UpgradeDef[] = [
  {
    id: "wifi",
    name: "Gigabit Wi-Fi",
    blurb: "+12% income per tier. Buffering is for the other building.",
    max: 8,
    cost: (level) => 280 * 7.5 ** level,
  },
  {
    id: "click",
    name: "Heavy Clickers",
    blurb: "Tapping desks pays more. Mechanical switches, obviously.",
    max: 10,
    cost: (level) => 70 * 5.4 ** level,
  },
  {
    id: "auto",
    name: "Office Manager",
    blurb: "Nico collects the cash so Rae can keep buying.",
    max: 1,
    cost: () => 18000,
  },
  {
    id: "offline",
    name: "Night Owls",
    blurb: "Earn 50% while away, up to eight hours. The Hum does not clock out.",
    max: 1,
    cost: () => 6500,
  },
  {
    id: "hr",
    name: "HR Handbook",
    blurb: "+5% income per hired desk. Written by people who were the policy.",
    max: 5,
    cost: (level) => 2200 * 6 ** level,
  },
];

export const IPO_STATIONS_REQUIRED = 8;
export const IPO_CASH_REQUIRED = 2_000_000;
export const UPGRADE_RATE = 0.2;
export const UPGRADE_COST_RATIO = 0.58;
export const UPGRADE_COST_GROWTH = 1.145;
export const MAX_STATION_LEVEL = 25;

export const OPENING =
  "Halcyon Consulting fired Rae Voss at 11:47pm on a Friday. By midnight she had a storage unit, a cardboard desk, and a list of people who would never 'circle back' again. You are building the floor that eats them.";
